Add SVG Picture
ShapeCrawler/ShapeCrawler pull request #675
Opened 2024-05-12 03:59 UTC by jcoliz

This extends `SlideShapes.AddPicture()` to allow adding SVG pictures.

It does not seem to matter what size the A.Blip gets rasterized at. I've experimented with very small resolutions, but when I load the file in PowerPoint, a proper-looking image is always shown. Ergo, it seems to be fine to simply for the user to add the svg picture and then resize in the usual way by changing the `Height` and `Width` properties. Perhaps a dedicated "resize" API is not needed.

In addition to the included unit tests, I have done some lightweight use-case testing. On Monday, I'll put this into my at-work workflow, which loads hundreds of images from many sources, and we'll see how it does there.

Fixes #350

2024-05-12 18:26 UTC, jcoliz commented
Last two commits above were done to pass sonarcloud. While I agree with its feedback, and think they are good changes, this now leads to the new code being dissimilar from the existing code. Up to you which is more important: Keeping sonarcloud happy, or congruence with existing code.

I suppose another option would be to make these changes to the existing code as well, so now sonarcloud is happy, code is improved, AND old/new code matches nicely.

2024-05-12 18:34 UTC, ashahabov requested changes

2024-05-12 18:34 UTC, ashahabov commented on src/ShapeCrawler/ShapeCollection/SlideShapes.cs
> +                throw new ArgumentException("Unable to decode image from supplied stream", nameof(imageStream));
Please use library custom class [SCException](https://github.com/ShapeCrawler/ShapeCrawler/blob/12982b7384a54285edf97fdded6820f6743245e4/src/ShapeCrawler/Exceptions/SCException.cs#L5) for exceptions.

2024-05-12 18:47 UTC, ashahabov commented
> Last two commits above were done to pass sonarcloud. While I agree with its feedback, and think they are good changes, this now leads to the new code being dissimilar from the existing code. Up to you which is more important: Keeping sonarcloud happy, or congruence with existing code.
> 
> I suppose another option would be to make these changes to the existing code as well, so now sonarcloud is happy, code is improved, AND old/new code matches nicely.


I suggest meeting the requirements of SonarCloud as much as possible, but it's better to avoid modifying code that isn't related to this task. This will help us prevent inflating the Pull Request.

2024-05-12 18:50 UTC, merged

2024-05-12 19:00 UTC, jcoliz commented
> > I suppose another option would be to make these changes to the existing code as well, so now sonarcloud is happy, code is improved, AND old/new code matches nicely.
> 
> I suggest meeting the requirements of SonarCloud as much as possible, but it's better to avoid modifying code that isn't related to this task. This will help us prevent inflating the Pull Request.

Right, making these changes to existing code would be a separate change, for sure, if you decided to go that route.

2024-05-18 23:19 UTC, jcoliz commented
@ashahabov I noticed this is still "In testing" in the project. I can say I've completed testing this with 200+ SVGs from many sources, and have reported all the issues found. In my own use, I've worked around every issue, and the results are stellar. So, I'd say this is looking good. We are going live on Tuesday with the results 😁

2024-05-19 16:52 UTC, ashahabov commented
@jcoliz, I believe, but I'd still like to try this out manually since this topic is new to me.

Reviewing PRs has a higher priority on my To-Do list🙂, so there is no time for another activities yet.

As a reminder, you can always if you need NuGet Package from the latest `master` you can get it from `https://www.myget.org/F/shape/api/v3/index.json` [Prerelease Version](https://github.com/ShapeCrawler/ShapeCrawler?tab=readme-ov-file#prerelease-version)

2024-05-20 04:12 UTC, jcoliz commented
@ashahabov No worries, just wanted to let you know how things were looking on my end.

I think I'm done with SVG PRs now , all known issues on my list addressed. Possibly will go after adding notes, but then you'll probably have a break from my PRs anyway.