Reuse existing image part
ShapeCrawler/ShapeCrawler pull request #826
Opened 2024-12-23 03:12 UTC by jcoliz

Initial first-pass implementation of image re-use. In the spirit of TDD, covers exactly and only the case in the first test: User has added second raster image (e.g. PNG) to the same slide in the same session.

Known gaps
* Vector images (i.e. SVG)
* Adding same image to presentation loaded from disk

Untested potential gaps
* Adding same image to another slide

Uses XML introspection to assert correct state, which goes against current conventions. However, I'd argue it's the best we have currently, and does allow for an automated test.

Fixes #809 (When complete)

2024-12-23 19:04 UTC, jcoliz commented
More mature implementation. Handles dupes across slides now. Still doesn't handle dupes across sessions, that's next.

2024-12-24 01:22 UTC, jcoliz commented
Ok, that worked better than expected. 30MB file is down to 4.5MB.

Discovered a missing use case. The following code results in duplicated images in `media` folder:

```c#
ISlides.Add(ISlide)
```

2024-12-24 01:49 UTC, jcoliz commented
This is the line where the images are duplicated:

```c#
internal readonly ref struct WrappedPresentationPart
...
    internal void AddSlidePart(SlidePart slidePart)
...
        var addedSlidePart = this.presentationPart.AddPart(slidePart, rId);
```

It's not obvious how to circumvent this. Ergo, let's call this feature done, and consider a possible future refinement where images are de-duped when slides are copied.

2024-12-29 11:54 UTC, ashahabov requested changes

2024-12-29 11:54 UTC, ashahabov commented on test/ShapeCrawler.Tests.Unit/Helpers/SCTest.cs
> +    protected void SavePresentationFile(IPresentation presentation)
`SCTest.SaveResult()` is a duplication and can be removed?

2024-12-29 11:54 UTC, ashahabov commented on test/ShapeCrawler.Tests.Unit/ShapeCollectionTests.cs
> +        SavePresentationFile(pres);
As mentioned [here](https://github.com/ShapeCrawler/ShapeCrawler/issues/803#issuecomment-2564385180), please avoid using Hard Drive if the test doesn't explicitly test integration with Hard Drive.

2024-12-29 11:54 UTC, ashahabov commented on test/ShapeCrawler.Tests.Unit/ShapeCollectionTests.cs
> +        imageParts.Count.Should().Be(2);
Is this assertion correct? Should be `imageParts.Count.Should().Be(1)`?

2025-01-01 01:33 UTC, jcoliz commented on test/ShapeCrawler.Tests.Unit/ShapeCollectionTests.cs
> +        imageParts.Count.Should().Be(2);
SVG adds two parts. One for vector image and one for raster. I should add a reason to these assertions.

2025-01-01 02:05 UTC, jcoliz commented on test/ShapeCrawler.Tests.Unit/ShapeCollectionTests.cs
> +        imageParts.Count.Should().Be(2);
b6cbf1b09058a4efb42f27fed36df448d55f9b6c

2025-01-01 02:12 UTC, jcoliz commented on test/ShapeCrawler.Tests.Unit/ShapeCollectionTests.cs
> +        SavePresentationFile(pres);
47f0f07b52a7210f7317700ce7e35847010eedc0

2025-01-01 02:12 UTC, jcoliz commented on test/ShapeCrawler.Tests.Unit/Helpers/SCTest.cs
> +    protected void SavePresentationFile(IPresentation presentation)
No longer. I have removed the potential duplication in addressing below comment. 47f0f07b52a7210f7317700ce7e35847010eedc0

2025-01-01 14:55 UTC, merged