Changed to use Magik package to support Mac and Linux
ShapeCrawler/ShapeCrawler pull request #830
Opened 2024-12-24 16:40 UTC by blockingHD

As an attempt to address the issue outlined in #823.

I changed the add picture method to use the [Magik.NET](https://github.com/dlemstra/Magick.NET?tab=Apache-2.0-1-ov-file) library. This supports all platforms with the AnyCPU package and is licenced under Apache 2.0. 

What are the thoughts on moving to this package? 
If this is acceptable, I will clean up the redundant code.

2024-12-24 18:09 UTC, jcoliz commented
@blockingHD As long as new library does everything the old one does, with no user impact, it sounds like a good change.

As a rule, replacing dependent libraries should not change any tests. The fact that this PR changes test assertions is a concern.

One specific comment I have so far is that the PR uses the rasterized dimensions for the shape size. We should not do that. We should use the precise SVG size. Rasterizing will lose precision, rounding to whole pixels. Sub-pixel precision is necessary.

I have a library of hundreds of SVGs, which I can run through this when it's ready.

2024-12-24 18:45 UTC, blockingHD commented
> @blockingHD As long as new library does everything the old one does, with no user impact, it sounds like a good change.
> 
> As a rule, replacing dependent libraries should not change any tests. The fact that this PR changes test assertions is a concern.
> 
> One specific comment I have so far is that the PR uses the rasterized dimensions for the shape size. We should not do that. We should use the precise SVG size. Rasterizing will lose precision, rounding to whole pixels. Sub-pixel precision is necessary.
> 
> I have a library of hundreds of SVGs, which I can run through this when it's ready.

Good point around the test changes. I assumed that this library was creating the PNG tighter to the true size of the SVG, given that it wouldn't be a surprise if a border were added. However, this could equally be my code so I will take more of a look.

2024-12-24 19:06 UTC, jcoliz commented
Yeah that particular file is exactly 90.0 x 276.9623. In fact, I probably should have gotten rid of the approximation in the test. The extent comes from this element:

```xml
<circle
   r="45"
   cx="231.9623"
   cy="45"
   fill="#ff0000"
   id="circle1-6" />
```

Also, this PR changes the rasterization DPI to 384. My view is that one PR should change one thing, to aid in focused review. Also, that's a change I'd like to discuss a bit more. I'll put my comments in that issue.

2024-12-24 19:27 UTC, blockingHD commented
@jcoliz I have looked at this; the height and widths are uint's, so Magik is adding imprecision and in the wrong direction! 
<img width="498" alt="image" src="https://github.com/user-attachments/assets/5e60cc2a-7dea-49a8-abab-db3597e25340" />

What do we want to do?

P.S. I can split the PPI change into a separate PR. I will look after there is a call re-making this change.

2024-12-24 22:28 UTC, jcoliz commented
Ok, so I have another idea. What if we entirely removed SVG processing from ShapeCrawler full stop. This would put rasterization on the user. Not super ideal, but it would avoid these dependency issues. As a side note, I'm worried about taking a dependency on AnyCPU architecture. Despite the name, it's still an architecture, and could cause issues with Win Arm. Removing SVG processing would avoid that too.

This could be implemented pretty easily. Add a second AddPicture signature to accept a SVG parameter. It means user would have to rasterize SVGs themselves, and pass the rasterized version in as the `image`, adding the svg as well. For tests, we can just add the rasterized PNG's to the test project.

```c#
public void AddPicture(Stream image, Stream svg)
```

Likewise, if user cares about precise sizing, we can put it on them too. We can accept the whole-pixel-precision sizing that comes from the user's rasterized image as the default. 

I'm curious to know if anyone else but me is using SVGs in ShapeCrawler 😁. For me, I'm already loading and measuring the SVG, so rasterizing it is simple.

2024-12-24 22:48 UTC, blockingHD commented
I am with you there @jcoliz the more I am looking at libraries and working out the pros and cons of each, the more I feel maybe this library should be agnostic. It would be ideal to have a default implementation, but as this is an architecture-specific task, then, as you say, an AnyCPU implementation still has limitations.

Further to this, PowerPoint seems to be dealing with SVGs entirely differently from the implementation for SVGs with no dimensions. This might just be a Mac thing? Which in fairness gives more weight to this argument. 

Guessing we need @ashahabov to make a call?

2024-12-24 22:53 UTC, jcoliz commented
> PowerPoint seems to be dealing with SVGs entirely differently from the implementation for SVGs with no dimensions. 

Please elaborate. As part of writing SVG support, I did a ton of work on the various permutations of dimensionless SVGs. Each of the SVGs in my collection is created by someone different, so this leads to a lot of variability. My goal was to match PowerPoint's outcome, as per design goals of the library. So I'd love to know what differences you're seeing.

2024-12-24 22:55 UTC, blockingHD commented
When adding the dimensionless SVG it gets inserted like this in PowerPoint:
<img width="1199" alt="Screenshot 2024-12-24 at 22 29 23" src="https://github.com/user-attachments/assets/3a514a5f-b6df-4649-a970-eba6350d689b" />

With the generated image being 2000x2000:
<img width="856" alt="Screenshot 2024-12-24 at 22 30 37" src="https://github.com/user-attachments/assets/5f2837d4-3370-49ee-8a8e-fa254b5dcc8b" />

2024-12-24 23:42 UTC, jcoliz commented
Ah, yes. Ok I think I decided that was so broken and unusable, there's no way user would want that to happen. This is a case where I think the library works _better_ than the UI. No reason we can't just infer dimensions from contents.

Having experimented with this a bit now, I've noticed a few things.
* If dimensions are set as fractional units, ImageMagick does the right thing and rounds UP, so the rasterized image looks good.
* In this case with un-set dimensions, ImageMagick actually slices off the right-most pixel, which isn't great. However, does it really matter? Rasterized image seems to be a formality. IIRC PowerPoint re-rasterizes on load anyway.
* ImageMagick AnyCPU library is compiling to native Arm64 binary no problem on Windows, so, looks like this won't cause a problem for this platform.

Maybe this is all fine as-written. Once you think it's ready, I can try on a pile of real data.

2024-12-25 00:07 UTC, jcoliz commented
Unfortunately, it seems that the current released code is actually broken in this case. In the test `AddPicture_adds_svg_picture_no_dimensions`, if we add a `pres.SaveAs`, and then load that up in PowerPoint, it is completely wrong. The dimensions match the source image, but it's actually the 2000x2000 image you showed, shrunk down to the "correct" size, so way too much white space.

I think the right course of action is to declare adding a dimensionless SVG "unsupported, producing undefined results," and remove the test.

2024-12-28 12:24 UTC, ashahabov commented
> Guessing we need @ashahabov to make a call?

Hello @blockingHD, hello @jcoliz.

I apologize for the silence. I just got back from vacation with my family yesterday. I am currently checking this PR along with others... I will back with my feedback...

Thanks for doing this hard work with images!

2024-12-28 19:13 UTC, blockingHD commented
I think this is ready for testing with your collection of SVGs @jcoliz.

I believe the SVG validity check is correct in that you must have a width and height or a view box to determine the size of the image. This isn't possible in an XSD, I don't think, as it requires logic around attributes which isn't supported. Please let me know if I am wrong!

Other than that, the only other thought I have is to throw a custom exception for the SVG failure to make it easier to catch. Not sure what other people think on that one.

2024-12-30 15:17 UTC, ashahabov commented
I think both of you have more experience with SVG content than I do, so I’m ready to go with whatever you think is the best. I just have a few limitations that I’ll share at the end below. First, let me explain the problem as I understand it. Please correct me if I’m wrong:

- The used SVG library doesn’t work on ARM-based macOS. Switching to Magick.NET has been suggested to solve this issue.
- The rendering quality of Magick.NET is worse than the current SVG library.

---

We had a similar [issue](https://github.com/ShapeCrawler/ShapeCrawler/issues/762#issuecomment-2409086910) before where a developer had a problem on Ubuntu. We solved it also by running `sudo apt install -y libgdiplus`. I agree with @blockingHD that we should document such solutions.

I'm not sure regard suggested `AddPicture(Stream image, Stream svg)`. It would be good to keep it as `AddPicture(Stream image)`. Can’t we detect if the `Stream` is SVG content and handle the rasterization automatically?

With SkiaSharp, the SVG library, and now Magick.NET, we are using three dependencies for graphics. We should try to reduce this to two. Either keep the SVG library or use Magick.NET, but three dependencies seem too much.

2025-01-01 01:31 UTC, jcoliz commented
@ashahabov This PR should remove SVG library dependency.

It's an interesting exercise for the future to see if ImageMagick could also replace SK image lib.

Add picture API with two streams would only be if you wanted to entirely remove any dependency related to SVG processing and put it on the user. It's extra work for SVG user but less dependencies for user not using SVG.

Please give me a couple days to test. Will be back at work later this week and want to test more there.

2025-01-01 10:33 UTC, ashahabov commented
> It's an interesting exercise for the future to see if ImageMagick could also replace SK image lib.

Yeah, that would be perfect.

2025-01-01 23:09 UTC, jcoliz requested changes
Couple comments from static review. Will try with images in next couple days.

2025-01-02 01:45 UTC, jcoliz commented
@blockingHD I don't think we can be thorough enough to test for all cases of missing height & width. I have an image that looks like this, which PowerPoint loads fine, but which triggers the "must have width or height" exception. IMO, we should accept undefined behavior here. Other solution is use a library, like SVG, which is likely to be sufficiently thorough, but obviously that's what we're trying to get away from.

```xml
<svg:svg
   version="1.1"
   id="Livello_1"
   x="0px"
   y="0px"
   viewBox="0 0 2744.5306 2553.2816"
   enable-background="new 0 0 2744.833 2553.333"
   xml:space="preserve"
   width="3.8889999in"
   height="3.618in"
```

2025-01-02 12:46 UTC, ashahabov commented on src/ShapeCrawler/ShapeCrawler.csproj
> +    <PackageReference Include="Magick.NET.SystemDrawing" Version="8.0.2" />
Yes.

2025-01-04 17:08 UTC, blockingHD commented on src/ShapeCrawler/ShapeCollection/SlideShapes.cs
> +                imageMagick.Resize((uint)width, (uint)height);
The logic here was just wrong. Though the height and width were being set but the image still need to be resized. Corrected now, so we constrain it to 500px then resize if it is 500px. This is slightly inefficient because what if the image was 500px to begin with but hardly seems worth worrying about.

I did have it where the height and width were constrained in the if block but SonarQube complained about cognative complexity. Not sure this is better but the machine told me to do it 😅

2025-01-04 17:21 UTC, ashahabov commented
@blockingHD, let me remind that you can see the code style issues locally building Release configuration instead of Debug.

2025-01-04 17:25 UTC, blockingHD commented
> @blockingHD, let me remind that you can see the code style issues locally building Release configuration instead of Debug.

I have built using the release config and I am not getting this error. So a little confused.

2025-01-04 17:45 UTC, ashahabov commented
@blockingHD, you should remove these unused usings:

![image](https://github.com/user-attachments/assets/257c65be-ca47-43ef-9f4d-b85f088ce185)

2025-01-04 17:48 UTC, blockingHD commented
@ashahabov Appologies, I was being a little silly. Did the merge in GitHub then never pulled the code back down. Should be fixed now :)

2025-01-04 18:58 UTC, ashahabov commented on test/ShapeCrawler.Tests.Unit/ShapeCollectionTests.cs
> -    public void AddPicture_adds_svg_picture_no_dimensions()
Are we abandoning this test `AddPicture_adds_svg_picture_no_dimensions`?

@jcoliz, I've run this test `AddPicture_adds_svg_picture_no_dimensions` on the latest changes of actual PR. It fails: The actual values:

```C#
picture.Height == 90
picture.Width == 276
```

2025-01-04 19:35 UTC, ashahabov commented
@blockingHD, I've added testing on macOS 13 (later also Ubuntu) in workflow Pull Request. Could you please back merge `master` branch to see whether it breaks something.

2025-01-04 21:10 UTC, blockingHD commented on test/ShapeCrawler.Tests.Unit/ShapeCollectionTests.cs
> -    public void AddPicture_adds_svg_picture_no_dimensions()
We had this failure earlier on. The new package doesn't calculate the size perfectly. However, due to how PowerPoint handles SVGs, the reality is that as soon as you save the PowerPoint, it gets recalculated incorrectly anyway. Hence, the suggestion of stating dimensionless SVGs produce undefined behaviour.

2025-01-05 03:25 UTC, jcoliz commented on test/ShapeCrawler.Tests.Unit/ShapeCollectionTests.cs
> -    public void AddPicture_adds_svg_picture_no_dimensions()
Yup. This test is not helpful. It's true, and it works, but the outcome is not what we want.

As an example, imagine a 200x100 solid black image. It will be correctly displayed as 200x100 in PowerPoint. However, the black area is scaled down to 20x5, and the remaining pixels are blank.

You can try by saving the result of this test to disk and then load in PowerPoint.

2025-01-07 01:22 UTC, jcoliz commented
FYI, ff7977199787c1b978263e786603869a5d605647 looks good to me. Tested against what I have, and all is well.

2025-01-08 12:41 UTC, ashahabov commented
@blockingHD, I've also finished testing, and I think it is ready to merge🎉 Please, back-merge `master` to resolve conflicts.

2025-01-08 18:27 UTC, blockingHD commented
@ashahabov This should be ready for approval and merging :)

2025-01-08 18:30 UTC, ashahabov commented on .github/workflows/pull request.yml
> -        os: [ windows-latest, ubuntu-latest, macos-13 ]
Please preserve also `ubuntu-latest`.

2025-01-08 18:33 UTC, ashahabov commented on test/ShapeCrawler.Tests.Unit/ShapeCollectionTests.cs
> -    public void AddPicture_should_not_duplicate_the_image_source_When_the_same_png_image_is_added_twice()
Please, do not remove this and another below `AddPicture_***` tests

2025-01-08 19:52 UTC, blockingHD commented on test/ShapeCrawler.Tests.Unit/ShapeCollectionTests.cs
> -    public void AddPicture_should_not_duplicate_the_image_source_When_the_same_png_image_is_added_twice()
This looks to have happened in the merge conflict commit you did. Do you want me just to revert that?

2025-01-08 19:57 UTC, ashahabov commented on test/ShapeCrawler.Tests.Unit/ShapeCollectionTests.cs
> -    public void AddPicture_should_not_duplicate_the_image_source_When_the_same_png_image_is_added_twice()
Yes, try to make revert to keep these tests or maybe it would be easier to just copy past these tests from origin `master`.

2025-01-08 20:00 UTC, ashahabov commented on .github/workflows/pull request.yml
> -            framework_version: 'net48'
Revert also these changes to prevent trying to test on .NET Framework 4.8 on `ubuntu-latest`.

2025-01-08 20:00 UTC, blockingHD commented on .github/workflows/pull request.yml
> -            framework_version: 'net48'
Should be sorted now.

2025-01-08 20:12 UTC, blockingHD commented on test/ShapeCrawler.Tests.Unit/ShapeCollectionTests.cs
> -    public void AddPicture_should_not_duplicate_the_image_source_When_the_same_png_image_is_added_twice()
The diff is borderline unintelligible but I think this is sorted now?

2025-01-08 20:35 UTC, ashahabov commented on test/ShapeCrawler.Tests.Unit/ShapeCollectionTests.cs
> -    public void AddPicture_should_not_duplicate_the_image_source_When_the_same_png_image_is_added_twice()
I've pushed some changes in your branch `Add-SVG-Support-For-Mac-and-Linux`. Please pull.

2025-01-08 20:39 UTC, merged